# Generated by Django 3.1.3 on 2021-08-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210831_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='open_bid_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
