# Generated by Django 3.1.3 on 2021-09-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210831_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(max_length=200),
        ),
    ]
