# Generated by Django 3.1.3 on 2021-09-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210901_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
