# Generated by Django 3.1.3 on 2021-09-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210902_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='item_id',
        ),
    ]
