# Generated by Django 3.1.3 on 2021-09-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210902_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='id',
        ),
    ]
